
#General settings
[general]
	#The CurseForge project ID for the modpack
	#Range: > 0
	modpackProjectID = 575342
	#The name of the modpack
	modpackName = "Create Tomorrow"
	#The version of the modpack
	modpackVersion = "0.0.3"
	#Use the metadata.json to determine the modpack version
	#ONLY ENABLE THIS IF YOU KNOW WHAT YOU ARE DOING
	useMetadata = false

